version: '3.3'
services:
  mongo:
    image: mongo:latest
    container_name: dkrcomp-mongo
    ports:
      - '27017:27017'
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=bdung
      - MONGO_INITDB_DATABASE=db